### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [fatih/pool#10]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for pool and versioning would help Debian keep up with development.

**Comment by fatih** [comment]
Hi @aviau 

It's already tagged, check out: https://github.com/fatih/pool/branches

It's currently v2.0.0 

Thanks!

**Comment by aviau** [comment]
Do you create a new branch every time you make a new commit, or implement a new feature?

**Comment by fatih** [comment]
Commits into master are not versioned. Once it's reach a stable condition I just tag a version.
