### ISSUE TITLE
How about using io.Closer instead of net.Conn?

### ISSUE THREAD

**Issue by tatsujin1** [fatih/pool#17]
So this would then be able to handle all "closable" objects?

**Comment by tatsujin1** [comment]
But it would then require a cast on user side to actually use the object returned from the pool.

**Comment by fatih** [comment]
I'm archiving and closing this project. It's not going to be maintained anymore. Thanks all for their valuable feedback and contributions. If you have questions, feel free to reach me from https://twitter.com/fatih
