### ISSUE TITLE
How to ensure the connection from the connection pool is not disconnect?

### ISSUE THREAD

**Issue by suntsh** [fatih/pool#6]
How to ensure the connection from the connection pool is not disconnect?

**Comment by aholic** [comment]
it's also the question i want to ask

**Comment by fatih** [comment]
You can't be sure. The only way you can know is trying to write/read from the connection. If it fails just go and fetch another connection from the pool.  Related https://groups.google.com/forum/#!msg/golang-nuts/MQs0M2rko38/kE4M9kH0f-0J
